### ISSUE TITLE
All tests time out.

### ISSUE THREAD

**Issue by Genoe** [maximilianschmitt/tutorial-rest-api-integration-testing-node-js#1]
Cloning and doing an npm install. Running npm run test and getting   `"before all" hook: startTestServer:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Repos\learning\integration testing\tutorial-rest-api-integration-testing-node-js\src\todos\__http-tests__\create-todo.test.js)`

causing all tests to fail.

**Comment by LamNoOne** [comment]
Hello @maximilianschmitt , your blog about this test is nice. But I meet some problems.
❯ yarn test
yarn run v1.22.22
warning package.json: No license field
$ mocha  "src/**/*.test.js"

(node:21338) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21338) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:21338) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:21338) Warning: Accessing non-existent property 'update' of module exports inside circular dependency
  POST /todos
    1) "before all" hook: startTestServer
    2) "after all" hook: stopTestServer

  GET /todos
(node:21381) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21381) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:21381) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:21381) Warning: Accessing non-existent property 'update' of module exports inside circular dependency

/mnt/d/workspace/intergration-test/tutorial-rest-api-integration-testing-node-js/node_modules/mongodb-core/lib/topologies/server.js:562
          new MongoNetworkError(
          ^
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1549:16) {
  name: 'MongoNetworkError',
  errorLabels: [Array],
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/mnt/d/workspace/intergration-test/tutorial-rest-api-integration-testing-node-js/node_modules/mongodb-core/lib/topologies/server.js:562:11)
    at Pool.emit (node:events:517:28)
    at Connection.<anonymous> (/mnt/d/workspace/intergration-test/tutorial-rest-api-integration-testing-node-js/node_modules/mongodb-core/lib/connection/pool.js:316:12)
    at Object.onceWrapper (node:events:632:26)
    at Connection.emit (node:events:517:28)
    at Socket.<anonymous> (/mnt/d/workspace/intergration-test/tutorial-rest-api-integration-testing-node-js/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (node:events:632:26)
    at Socket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3) {
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {}
}

Node.js v18.19.1
    3) "before all" hook: startTestServer
    4) "after all" hook: stopTestServer

  PATCH /todos/:todoId
(node:21402) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21402) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:21402) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:21402) Warning: Accessing non-existent property 'update' of module exports inside circular dependency

/mnt/d/workspace/intergration-test/tutorial-rest-api-integration-testing-node-js/node_modules/mongodb-core/lib/topologies/server.js:562
          new MongoNetworkError(
          ^
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1549:16) {
  name: 'MongoNetworkError',
  errorLabels: [Array],
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/mnt/d/workspace/intergration-test/tutorial-rest-api-integration-testing-node-js/node_modules/mongodb-core/lib/topologies/server.js:562:11)
    at Pool.emit (node:events:517:28)
    at Connection.<anonymous> (/mnt/d/workspace/intergration-test/tutorial-rest-api-integration-testing-node-js/node_modules/mongodb-core/lib/connection/pool.js:316:12)
    at Object.onceWrapper (node:events:632:26)
    at Connection.emit (node:events:517:28)
    at Socket.<anonymous> (/mnt/d/workspace/intergration-test/tutorial-rest-api-integration-testing-node-js/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (node:events:632:26)
    at Socket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3) {
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {}
}

Node.js v18.19.1
    5) "before all" hook: startTestServer
    6) "after all" hook: stopTestServer


  0 passing (3s)
  6 failing

  1) POST /todos
       "before all" hook: startTestServer:
     Error: URL http://localhost:38557 not reachable after 1000ms
      at waitForURLReachable (test-helpers/test-server.js:48:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

  2) POST /todos
       "after all" hook: stopTestServer:
     TypeError: Cannot read properties of undefined (reading 'kill')
      at Context.stopTestServer (test-helpers/test-server.js:81:21)
      at process.processImmediate (node:internal/timers:476:21)

  3) GET /todos
       "before all" hook: startTestServer:
     Error: URL http://localhost:44257 not reachable after 1000ms
      at waitForURLReachable (test-helpers/test-server.js:48:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

  4) GET /todos
       "after all" hook: stopTestServer:
     TypeError: Cannot read properties of undefined (reading 'kill')
      at Context.stopTestServer (test-helpers/test-server.js:81:21)
      at process.processImmediate (node:internal/timers:476:21)

  5) PATCH /todos/:todoId
       "before all" hook: startTestServer:
     Error: URL http://localhost:46415 not reachable after 1000ms
      at waitForURLReachable (test-helpers/test-server.js:48:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

  6) PATCH /todos/:todoId
       "after all" hook: stopTestServer:
     TypeError: Cannot read properties of undefined (reading 'kill')
      at Context.stopTestServer (test-helpers/test-server.js:81:21)
      at process.processImmediate (node:internal/timers:476:21)



(node:21417) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21417) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:21417) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:21417) Warning: Accessing non-existent property 'update' of module exports inside circular dependency

/mnt/d/workspace/intergration-test/tutorial-rest-api-integration-testing-node-js/node_modules/mongodb-core/lib/topologies/server.js:562
          new MongoNetworkError(
          ^
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1549:16) {
  name: 'MongoNetworkError',
  errorLabels: [Array],
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/mnt/d/workspace/intergration-test/tutorial-rest-api-integration-testing-node-js/node_modules/mongodb-core/lib/topologies/server.js:562:11)
    at Pool.emit (node:events:517:28)
    at Connection.<anonymous> (/mnt/d/workspace/intergration-test/tutorial-rest-api-integration-testing-node-js/node_modules/mongodb-core/lib/connection/pool.js:316:12)
    at Object.onceWrapper (node:events:632:26)
    at Connection.emit (node:events:517:28)
    at Socket.<anonymous> (/mnt/d/workspace/intergration-test/tutorial-rest-api-integration-testing-node-js/node_modules/mongodb-core/lib/connection/connection.js:245:50)
    at Object.onceWrapper (node:events:632:26)
    at Socket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3) {
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {}
}
Actually i also run yarn run dev to start server due to call api.
I don't know how you can test successfully on the post. I spent a lot of time for that since your clear and helpful post, but the code not.
